services:
  backend:
    build: ./backend/.
    image: app-backend:latest
    container_name: backend
    ports:
      - "8000"
    env_file:
      - env_files_for_docker/backend.env
    restart: unless-stopped
    networks:
      - freelance
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      worker:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend/.
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - env_files_for_docker/frontend.env
    restart: unless-stopped
    networks:
      - freelance
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
  worker:
    image: app-backend:latest
    container_name: worker
    entrypoint: []
    env_file:
      - env_files_for_docker/backend.env
    environment:
      - PYTHONPATH=src
    command: [ "uv", "run", "celery", "-A", "core.email_message", "worker", "-l", "INFO" ]
    restart: unless-stopped
    networks:
      - freelance
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    container_name: db
    env_file:
      - env_files_for_docker/pg.env
    networks:
      - freelance
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d freelance" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8-alpine
    container_name: redis
    networks:
      - freelance
    ports:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  freelance:
    driver: bridge

volumes:
  pgdata:
    name: freelance_pgdata
    external: true
