services:
  backend:
    image: p1app/freelance_backend
    container_name: backend
    expose:
      - 8000
    env_file:
      - env/backend.env
    restart: unless-stopped
    networks:
      - freelance
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
    depends_on:
      worker:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      loki:
        condition: service_started

  frontend:
    image: p1app/freelance_frontend
    container_name: frontend
    ports:
      - "5173:80"
    env_file:
      - env/frontend.env
    restart: unless-stopped
    networks:
      - freelance
    depends_on:
      backend:
        condition: service_healthy
  worker:
    image: p1app/freelance_backend
    container_name: worker
    entrypoint: []
    env_file:
      - env/backend.env
    environment:
      - PYTHONPATH=src
    command: [ "uv", "run", "--frozen", "--no-group", "dev", "celery", "-A", "core.email_message", "worker", "-l", "INFO" ]
    restart: unless-stopped
    networks:
      - freelance
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: postgres:18-alpine
    container_name: db
    expose:
      - 5432
    env_file:
      - env/pg.env
    networks:
      - freelance
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d freelance" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:8-alpine
    container_name: redis
    networks:
      - freelance
    ports:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
  prometheus:
    image: prom/prometheus:v3.15.0
    container_name: prometheus
    networks:
      - freelance
    expose:
      - 9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  node-exporter:
    image: prom/node-exporter:v1-distroless
    container_name: node-exporter
    networks:
      - freelance
    expose:
      - 9100
    pid: "host"
    volumes:
      - /:/host:ro, rslave
    command:
      - '--path.rootfs=/host'


  grafana:
    image: grafana/grafana:13.0-slim
    container_name: grafana
    networks:
      - freelance
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    networks:
      - freelance
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    networks:
      - freelance
    ports:
      - "12345:12345"  
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_data:/var/lib/alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki

volumes:
  loki_data:
    name: loki_freelance_data
  alloy_data:
    name: alloy_freelance_data
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data

  grafana_data:
    name: grafana_data

  pgdata:
    name: freelance_pgdata
    # external: true

networks:
  freelance:
    driver: bridge