"""fix users.completed_projects

Revision ID: 007956e02815
Revises: ac0f7b3dc882
Create Date: 2026-09-13 18:59:40.363061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007956e02815'
down_revision: Union[str, Sequence[str], None] = 'ac0f7b3dc882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_projects', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'compeleted_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('compeleted_projects', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'completed_projects')
    # ### end Alembic commands ###
