name: 'CI_CD' 
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v7
        - name: 'Install uv'
          uses: astral-sh/setup-uv@v5
        - name: 'Linting with ruff'
          run: uv run -С backend ruff check ./src ./tests
        - name: 'Check error with ty'
          run: uv run -С backend ty check ./src ./tests 
    # test:
    #   runs-on: ubuntu-latest
    #   services:
